"""initial_schema

Revision ID: 3c8dfe750fef
Revises: 
Create Date: 2026-10-09 13:33:03.423826

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c8dfe750fef'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_execution_id'), 'analyses', ['execution_id'], unique=True)
    op.create_index(op.f('ix_analyses_patient_id'), 'analyses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_execution_id'), 'audit_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_audit_events_patient_id'), 'audit_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_page_number'), 'document_pages', ['page_number'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_category'), 'guideline_chunks', ['category'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_knowledge_base_id'), 'guideline_chunks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_organization'), 'guideline_chunks', ['organization'], unique=False)
    op.create_index(op.f('ix_observations_category'), 'observations', ['category'], unique=False)
    op.create_index(op.f('ix_observations_code'), 'observations', ['code'], unique=False)
    op.create_index(op.f('ix_observations_document_id'), 'observations', ['document_id'], unique=False)
    op.create_index(op.f('ix_observations_flag'), 'observations', ['flag'], unique=False)
    op.create_index(op.f('ix_observations_name'), 'observations', ['name'], unique=False)
    op.create_index(op.f('ix_observations_observation_date'), 'observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=True)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_medical_record_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_date'), table_name='observations')
    op.drop_index(op.f('ix_observations_name'), table_name='observations')
    op.drop_index(op.f('ix_observations_flag'), table_name='observations')
    op.drop_index(op.f('ix_observations_document_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_code'), table_name='observations')
    op.drop_index(op.f('ix_observations_category'), table_name='observations')
    op.drop_index(op.f('ix_guideline_chunks_organization'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_guideline_chunks_knowledge_base_id'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_guideline_chunks_category'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_document_pages_page_number'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_patient_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_execution_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_analyses_patient_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_execution_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    # ### end Alembic commands ###
